#define SUCCESS 0x00
#define ERROR 0xFF
#define MAX_PROCESS 20
#define MIN_PROCESS 5
#define SLAVE_PROCESS_LIVE_TIME 100
#define PROGRAM_NAME 0
#define PROGRAM_FLAG 1
#define PROGRAM_SLAVE_PROCESS_TIME 2
#define PROGRAM_TOTAL_PROCESS 3
#define SEM_PERMISSION 0777


